### ISSUE TITLE
which gke version satisfied chart version 0.0.9 ?

### ISSUE THREAD

**Issue by jpuyy** [sagikazarmark/helm-charts#29] opened 2021-01-28 06:25 UTC
helm3.4.0 install --generate-name --wait skm/sftpgo
Error: chart requires kubeVersion: >=1.16 which is incompatible with Kubernetes v1.16.15-gke.6000

**Comment by sagikazarmark** [comment] 2021-02-02 01:07
Duplicate of #30

**Closed by sagikazarmark** 2021-02-02 01:07 UTC
